### ISSUE TITLE
Should support OAuth setup for users w/o access, refresh token

### ISSUE THREAD

**Issue by pgorsira** [coinbase/coinbase-python#1]
The old coinbase-python had functions for steps involved in the OAuth process. This library should support more than just making calls as the already-OAuthed user.

**Comment by pgorsira** [comment]
Nvm, appears I was mistaken, the other library just has a nice example included that makes use of other 3rd party libs: https://github.com/sibblegp/coinbase_python/blob/master/coinbase_oauth2/__init__.py

**Comment by jorilallo** [comment]
@pgorsira As implementing OAuth2 flow is pretty specific to web framework of your choosing we decided to leave it out in this library. We'll be including more tools to our documentation etc to help.

I would highly recommend checking out [python-social-auth](https://github.com/omab/python-social-auth). I have used it in the past and it's pretty flexible. Otherwise, implementing it from scratch doesn't take too much effort as long as you remember to supply `state` param to protect your users from CSRF attacks.
