### ISSUE TITLE
Bug with get_address_transactions

### ISSUE THREAD

**Issue by fostiropoulos** [coinbase/coinbase-python#48]
So I am using coinbase API and the python library available by them. 

    accounts = client.get_accounts()
    
    accountId=accounts["data"][0]["id"]    
    print(client.get_address_transactions(accountId, id))

The above returns 

    {
      "data": []
    }

But if I do:

    txs = client.get_transactions(accountId)
    print(txs["data"][0])

I get the following results:

    {
      "address": {
        "id": id, 
        "resource": "address", 
        "resource_path": 
      }, 
      ......
      "status": "completed", 
      "type": "send"
    }

It doesn't make sense, I have send money to myself to test this feature and the transactions don't seem to show in that api call. 

The IDs are the same

**Comment by AchillesFirstStand** [comment]
Did you find a solution to this? I am also having result: "data": []
I want the result to be my transactions.

**Comment by sds** [comment]
Hey @fostiropoulos, thanks for the report.

Since this appears to be an issue with values returned from the API (and not an issue with this Python package), please contact our [support team](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-) to assist with figuring this out. Thanks!
